name: Linux GNU
# triggered events (push, pull_request) for the develop branch
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  ubuntu_build:
    name: Ubuntu GNU Build
    # Run on ubuntu-latest
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      # Install OpenMPI
      - name: Install OpenMPI
        run: sudo apt-get install openmpi-bin libopenmpi-dev -y

      # Test debug mode
      #- name: Build gf debug
      #  run: |
      #    cd ref
      #    rm -rf build
      #    mkdir build
      #    cd build
      #    export OMP_NUM_THREADS=4
      #    export CC=gcc
      #    export FC=gfortran
      #    cmake -DCMAKE_BUILD_TYPE=debug ..
      #    make
      #    ctest --output-on-failure

      # Test release mode
      - name: Build gf release
        run: |
          cd ref
          rm -rf build
          mkdir build
          cd build
          #export OMP_NUM_THREADS=4
          export CC=gcc
          export FC=gfortran
          cmake -DCMAKE_BUILD_TYPE=release -DENABLE_GPU=off ..
          make
          ctest --output-on-failure
